# Docker MCP Stack - Prometheus Configuration

global:
    scrape_interval: 15s
    evaluation_interval: 15s
    scrape_timeout: 10s
    external_labels:
        cluster: "mcpai-stack"

# Rule files
rule_files:
    - "rules/*.yml"

# Alerting configuration
alerting:
    alertmanagers:
        - static_configs:
              - targets:
                # - alertmanager:9093

# Scrape configs
scrape_configs:
    # Self monitoring
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]
      scrape_interval: 15s

    # MCP API Service
    - job_name: "mcp-api"
      metrics_path: /metrics
      static_configs:
          - targets: ["mcp-api:4000"]
      scrape_interval: 5s
      scrape_timeout: 5s
      honor_labels: true

    # Mock Model Runner (for testing)
    - job_name: "mock-model-runner"
      metrics_path: /metrics
      static_configs:
          - targets: ["mock-model-runner:8080"]
      scrape_interval: 5s
      scrape_timeout: 5s

    # Model Runner Service
    - job_name: "model-runner"
      metrics_path: /metrics
      static_configs:
          - targets: ["model-runner:8080"]
      scrape_interval: 5s
      scrape_timeout: 5s

    # Qdrant Vector Database
    - job_name: "qdrant"
      metrics_path: /metrics
      static_configs:
          - targets: ["qdrant:6333"]
      scrape_interval: 10s

    # UI Service (if it has metrics)
    - job_name: "ui"
      metrics_path: /metrics
      static_configs:
          - targets: ["ui:8501"]
      scrape_interval: 10s

    # Docker daemon metrics (if enabled)
    - job_name: "docker"
      static_configs:
          - targets: ["host.docker.internal:9323"]
      scrape_interval: 30s

    # Node Exporter for host metrics (if deployed)
    - job_name: "node-exporter"
      static_configs:
          - targets: ["node-exporter:9100"]
      scrape_interval: 30s

    # Grafana metrics
    - job_name: "grafana"
      static_configs:
          - targets: ["grafana:3000"]
      metrics_path: /metrics
      scrape_interval: 30s

    # Loki metrics
    - job_name: "loki"
      static_configs:
          - targets: ["loki:3100"]
      metrics_path: /metrics
      scrape_interval: 30s
# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"

# Storage configuration
# Note: These are command-line flags, not YAML config
# --storage.tsdb.retention.time=30d
# --storage.tsdb.retention.size=10GB
