groups:
  - name: mcpai-stack-alerts
    rules:
      # Service Health Alerts
      - alert: ServiceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 5 minutes."

      # High CPU Usage
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.job }}"
          description: "CPU usage is above 80% for more than 10 minutes on {{ $labels.job }}."

      # High Memory Usage
      - alert: HighMemoryUsage
        expr: (process_resident_memory_bytes / 1024 / 1024) > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.job }}"
          description: "Memory usage is above 1GB on {{ $labels.job }}."

      # HTTP Error Rate
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{status_code=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP error rate on {{ $labels.job }}"
          description: "HTTP error rate is above 10% for {{ $labels.job }}."

      # Request Duration
      - alert: HighRequestDuration
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High request duration on {{ $labels.job }}"
          description: "95th percentile request duration is above 1 second for {{ $labels.job }}."

      # Qdrant specific alerts
      - alert: QdrantCollectionDown
        expr: qdrant_collections_total == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Qdrant has no collections"
          description: "Qdrant vector database has no collections available."

      # Model Runner specific alerts
      - alert: ModelRunnerUnhealthy
        expr: model_runner_health == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Model runner is unhealthy"
          description: "Model runner health check is failing."

  - name: mcpai-stack-recording-rules
    rules:
      # Recording rules for common metrics
      - record: job:http_requests:rate5m
        expr: sum(rate(http_requests_total[5m])) by (job)

      - record: job:http_request_duration:p95
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (job, le))

      - record: job:http_request_duration:p50
        expr: histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (job, le))

      - record: job:active_requests:avg
        expr: avg(active_requests) by (job)
