# Docker MCP Stack - Development Configuration
# Hot-reload and development-specific settings

version: "3.9"

# Use anchors for DRY and modern Compose
x-common-env: &common-env
    QDRANT_URL: http://qdrant:6333
    OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://model-runner:8080/v1}
    MODEL_API_URL: http://model-runner:8080/v1
    PROMETHEUS_MULTIPROC_DIR: /tmp
    PYTHONUNBUFFERED: 1

services:
    # Development overrides for hot-reload
    mcp-api:
        volumes:
            - ../services/mcp-api/src:/app/src:ro
            - mcp_data:/data
        command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "4000", "--reload"]
        environment:
            <<: *common-env

    mcp-worker:
        volumes:
            - ../services/mcp-worker/src:/app/src:ro
            - mcp_data:/data
            - worker_temp:/tmp
        command: ["python", "-m", "src.worker", "--reload"]
        environment:
            <<: *common-env

    ui:
        volumes:
            - ../services/ui/src:/app/src:ro
        command:
            [
                "streamlit",
                "run",
                "src/app.py",
                "--server.port",
                "8501",
                "--server.address",
                "0.0.0.0",
                "--server.fileWatcherType",
                "poll",
            ]
        environment:
            <<: *common-env
            STREAMLIT_SERVER_PORT: 8501
            STREAMLIT_SERVER_ADDRESS: 0.0.0.0

    # Model runner with mounted source for development
    model-runner:
        volumes:
            - ../services/model-runner/src:/app/src:ro
            - models_cache:/models
            - model_config:/config
        environment:
            <<: *common-env
